### ISSUE TITLE
Players Can Aim & Shoot When Inside UI

### ISSUE THREAD

**Issue by yiruzu** [Byte-Labs-Project/bl_customs#15]
(also steer but its not a big deal and maybe even helpful for some people)

**Comment by yiruzu** [comment]
I would just use the `SetNuiFocusKeepInput` native and when the player clicks on preview it gets set to true, but it should be false by default so they can't do stupid stuff when inside the UI:

**Comment by yiruzu** [comment]
this would also obv fix the map from opening when pressing esc

**Comment by Frowmza** [comment]
Fixed! https://github.com/Byte-Labs-Project/bl_customs/commit/6e3150e0fb401b57ca4cfa208a7e541f3e5d2d74
