### ISSUE TITLE
You should not trust anything submitted by the client, especially the price.

### ISSUE THREAD

**Issue by iwanttodo1t** [Byte-Labs-Project/bl_customs#20]
When a player modifies a car, he should submit the modification content to the server. The server calculates the price based on the content and compares it with the price submitted by the client.

**Comment by Frowmza** [comment]
There's no way someone can change the data of local functions in a script or config files. Also, vehicle modification natives are all client-side, so if someone is actually injecting, they could fully modify the vehicle for free.
