### ISSUE TITLE
No such export core in resource bl_bridge - Latest downloaded both scripts

### ISSUE THREAD

**Issue by Duguayster** [Byte-Labs-Project/bl_customs#7]
![image](https://github.com/Byte-Labs-Project/bl_customs/assets/31002773/fe8885f1-099a-4cbd-8477-f34fa4b28abb)

![image](https://github.com/Byte-Labs-Project/bl_customs/assets/31002773/b58f7708-cd24-4797-89d0-f324a3621abe)

Hello,

I have both bl_customs and bl_bridge updated to the latest version. This error occurs when I attempt to pull into one of the LS Customs locations.

**Comment by Frowmza** [comment]
do you start bridge before customs?

**Comment by Duguayster** [comment]
Yes, it's only after I updated my blcustom from version 1.0.0 to this one on github that I started having this error.

**Comment by Frowmza** [comment]
please recheck and reinstall

**Comment by Duguayster** [comment]
All good one of the files I had was corrupt worked after deleting, redownload and reinstall. My bad.

**Comment by Duguayster** [comment]
Fixed
