### ISSUE TITLE
No turbo option in menu

### ISSUE THREAD

**Issue by jsanvall** [Byte-Labs-Project/bl_customs#8]
Hi. 

I'm installing this script on my server and I cannot find the "Turbo" enabler option, even if I set it on the config.lua file with the following: 

```
Turbo =                   {id = 18, price = 0, cam = {angle = vec2(127.125, 33.0), off = vec3(-3.200000, 3.400000, 2.100000)}},
```

Also tried:
```
['Turbo'] = {
            id = 18,
            labels = {
                [0] = {label = 'Turbo On', price = 0},
            }
        },
```

FiveM Docs says that the Turbo ID is '18' but It doesn't appear on my menu. 

Any idea of what I'm doing wrong? Am I missing something?

**Comment by Frowmza** [comment]
turbo is a toggle, will add it soon

**Comment by Frowmza** [comment]
added!
